### Pengolahan Data dengan Pandas
### Dipersiapkan oleh Ridowati G
### LAST UPDATE : 7 Mei 2023
### 3. Viewing Data

In [6]:
import pandas as pd
dataku=pd.read_csv("kapal_titanic.csv")
dataku

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [7]:
# Menampilkan dari awal
import pandas as pd
dataku=pd.read_csv("kapal_titanic.csv")
data_top=dataku.head()
data_top

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [8]:
#dataajkhir
dataku.tail

<bound method NDFrame.tail of      survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]>

In [9]:
# menampilkan awal sebanyak 10
dataku.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN
5         0       3    male   NaN      0      0   8.4583        Q  NaN
6         0       1    male  54.0      0      0  51.8625        S    E
7         0       3    male   2.0      3      1  21.0750        S  NaN
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [10]:
import pandas as pd
dataku=pd.read_csv("nba.csv")
#pd.options.display.max_rows=900
dataku

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [11]:
dataku

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [12]:
#Menampilkan 10 data teratas dari column Name


In [4]:
# Menampilkan 10 data terakhir dari column salary
import pandas as pd
dataku=pd.read_csv('nba.csv')
series=dataku['Salary']
bottom=series.tail(9)
bottom

449    1348440.0
450    2050000.0
451     981348.0
452    2239800.0
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, dtype: float64

In [ ]:
# Menampilkan info
dataku.head()

In [ ]:
dataku.info()

In [13]:
# statistik deskriptive khusus untuk data numeric (type<>object)
dataku.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
# statistik deskriptive khusus untuk data nonnumeric (type=object)
dataku.describe(include='O')

Install beberapa library untuk membaca berbagai tipe data
1. openpyxl --> xls
2. xlrd --> Excel
3. lxml --> HTML
4. html5lib --> HTML    
5. BeautifulSoup4 -->  HTML
6. Sqlalchemy --> Sql

In [15]:
## Import data ke tipe lain
## Indexnya dibuat false, jika tidak maka akan jadi column; 
## coba untuk tidak menggunakan index
dataku.to_csv('datacsv.csv',index=False)
#dataku.to_csv('datacsv.csv')

In [16]:
dataku=pd.read_csv('datacsv.csv')

In [17]:
dataku

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
3    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
4     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
..             ...             ...     ...      ...   ...    ...     ...   
359    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
360  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
361     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
362   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
363    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

           College     Salary  
0            Texas  7730337.0  
1        Marquette  6796117.0  
2    Georgia State  1148640.0  
3              LSU  1170960.0  
4          Gonzaga  2165160.0  
..             ...        ...  
359           Duke  1348440.0  
360         Dayton   981348.0  
361       Kentucky  2239800.0  
362         Butler  2433333.0  
363         Kansas   947276.0  

[364 rows x 9 columns]

In [18]:
#Import ke xlsx
dataku.to_excel('dataexcel.xlsx',index=False,sheet_name='coba')

In [20]:
# baca data html
datahtml=pd.read_html("https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/")
datahtml[0]

Bank NameBank           CityCity StateSt  CertCert  \
0                  First Republic Bank      San Francisco      CA     59017   
1                       Signature Bank           New York      NY     57053   
2                  Silicon Valley Bank        Santa Clara      CA     24735   
3                    Almena State Bank             Almena      KS     15426   
4           First City Bank of Florida  Fort Walton Beach      FL     16748   
..                                 ...                ...     ...       ...   
561                 Superior Bank, FSB           Hinsdale      IL     32646   
562                Malta National Bank              Malta      OH      6629   
563    First Alliance Bank & Trust Co.         Manchester      NH     34264   
564  National State Bank of Metropolis         Metropolis      IL      3815   
565                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
1                    Flagstar Bank, N.A.      March 12, 2023     10540  
2    First–Citizens Bank & Trust Company      March 10, 2023     10539  
3                            Equity Bank    October 23, 2020     10538  
4              United Fidelity Bank, fsb    October 16, 2020     10537  
..                                   ...                 ...       ...  
561                Superior Federal, FSB       July 27, 2001      6004  
562                    North Valley Bank         May 3, 2001      4648  
563  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
564              Banterra Bank of Marion   December 14, 2000      4646  
565                   Bank of the Orient    October 13, 2000      4645  

[566 rows x 7 columns]

In [24]:
#Convert data pandas DataFrame to numpy Array

# Syntax : DataFrame.to_numpy(dtype=None,copy=False)
# Return : numpy.ndarray

import pandas as pd
 
# initialize a dataframe
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]],
    columns=['a', 'b', 'c'])
df



# convert dataframe to numpy array
arr = df.to_numpy()
 
print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [25]:
import pandas as pd
 
# initialize a dataframe
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]],
    columns=['a', 'b', 'c'])
 
# convert dataframe to numpy array
arr = df[['a', 'c']].to_numpy()
 
print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]
<class 'numpy.ndarray'>
